# Generated by Django 3.0.7 on 2021-01-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210121_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='msg_date',
            new_name='message_date',
        ),
    ]
