# Generated by Django 3.0.4 on 2021-01-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
