# Generated by Django 3.0.4 on 2021-01-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210125_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_created',
            new_name='created',
        ),
    ]
